MarvelEncounterSets <- function(marvelGlm) {
  coefs <- coef(marvelGlm)
  return(data.frame(
    row.names = c(
      " - Core Set - ",
      "Bomb Scare",
      "Masters of Evil",
      "Under Attack",
      "Legions of Hydra",
      "Doomsday Chair",
      " - Green Goblin - ",
      "Goblin Gimmicks",
      "Mess of Things",
      "Power Drain",
      "Running Interference",
      "Kree Fanatic",
      " - Rise of Red Skull - ",
      "Experimental Weapons",
      "Hydra Assault",
      "Hydra Patrol",
      "Weapon Master",
      " - Kang - ",
      "Temporal",
      "Master of Time",
      "Anachronauts",
      " - Galaxy's Most Wanted - ",
      "Band of Badoon",
      "Menagerie Medley",
      "Galactic Artifacts",
      "Space Pirates",
      "Kree Militants",
      "Ship Command",
      "Badoon Headhunter",
      " - Mad Titan's Shadow - ",
      "Black Order",
      "Armies of Titan",
      "Children of Thanos",
      "Legions of Hel",
      "Frost Giants",
      "Enchantress",
      "Infinity Gauntlet",
      " - The Hood - ",
      "Beasty Boys",
      "Brothers Grimm",
      "Crossfire's Crew",
      "Mister Hyde",
      "Ransacked Armory",
      "Sinister Syndicate",
      "State of Emergency",
      "Streets of Mayhem",
      "Wrecking Crew",
      " - Sinister Motives - ",
      "City in Chaos",
      "Down to Earth",
      "Goblin Gear",
      "Guerrilla Tactics",
      "Osborn Tech",
      "Personal Nightmare",
      "Sinister Assault",
      "Symbiotic Strength",
      "Whispers of Paranoia",
      " - Hero Packs - ",
      "Armadillo",
      "Zzzax",
      "The Inheritors",
      "Iron Spider's Sinister Six",
      "Deathstrike",
      "Shadow King",
      " - Mutant Genesis - ",
      "Acolytes",
      "Brotherhood",
      "Future Past",
      "Mystique",
      "Sentinels",
      "Zero Tolerance",
      " - Mojo Mania - ",
      "Crime",
      "Fantasy",
      "Horror",
      "Sci-Fi",
      "Sitcom",
      "Western",
      "Longshot",
      "",
      "Expert",
      "Heroic",
      "Skirmish Level 1",
      "Skirmish Level 2",
      "Standard II",
      "Expert II"
    ),
    Ratings = c(
      "",
      sprintf("%+d", round(coefs["BombScareTRUE"] * 10)),
      sprintf("%+d", round(coefs["MastersOfEvilTRUE"] * 10)),
      sprintf("%+d", round(coefs["UnderAttackTRUE"] * 10)),
      sprintf("%+d", round(coefs["LegionsOfHydraTRUE"] * 10)),
      sprintf("%+d", round(coefs["DoomsdayChairTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["GoblinGimmicksTRUE"] * 10)),
      sprintf("%+d", round(coefs["MessOfThingsTRUE"] * 10)),
      sprintf("%+d", round(coefs["PowerDrainTRUE"] * 10)),
      sprintf("%+d", round(coefs["RunningInterferenceTRUE"] * 10)),
      sprintf("%+d", round(coefs["KreeFanaticTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["ExperimentalWeaponsTRUE"] * 10)),
      sprintf("%+d", round(coefs["HydraAssaultTRUE"] * 10)),
      sprintf("%+d", round(coefs["HydraPatrolTRUE"] * 10)),
      sprintf("%+d", round(coefs["WeaponMasterTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["TemporalTRUE"] * 10)),
      sprintf("%+d", round(coefs["MasterOfTimeTRUE"] * 10)),
      sprintf("%+d", round(coefs["AnachronautsTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["BandOfBadoonTRUE"] * 10)),
      sprintf("%+d", round(coefs["MenagerieMedleyTRUE"] * 10)),
      sprintf("%+d", round(coefs["GalacticArtifactsTRUE"] * 10)),
      sprintf("%+d", round(coefs["SpacePiratesTRUE"] * 10)),
      sprintf("%+d", round(coefs["KreeMilitantsTRUE"] * 10)),
      sprintf("%+d", round(coefs["ShipCommandTRUE"] * 10)),
      sprintf("%+d", round(coefs["BadoonHeadhunterTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["BlackOrderTRUE"] * 10)),
      sprintf("%+d", round(coefs["ArmiesOfTitanTRUE"] * 10)),
      sprintf("%+d", round(coefs["ChildrenOfThanosTRUE"] * 10)),
      sprintf("%+d", round(coefs["LegionsOfHelTRUE"] * 10)),
      sprintf("%+d", round(coefs["FrostGiantsTRUE"] * 10)),
      sprintf("%+d", round(coefs["EnchantressTRUE"] * 10)),
      sprintf("%+d", round(coefs["InfinityGauntletTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["BeastyBoysTRUE"] * 10)),
      sprintf("%+d", round(coefs["BrothersGrimmTRUE"] * 10)),
      sprintf("%+d", round(coefs["CrossfiresCrewTRUE"] * 10)),
      sprintf("%+d", round(coefs["MisterHydeTRUE"] * 10)),
      sprintf("%+d", round(coefs["RansackedArmoryTRUE"] * 10)),
      sprintf("%+d", round(coefs["SinisterSyndicateTRUE"] * 10)),
      sprintf("%+d", round(coefs["StateOfEmergencyTRUE"] * 10)),
      sprintf("%+d", round(coefs["StreetsOfMayhemTRUE"] * 10)),
      sprintf("%+d", round(coefs["WreckingCrewTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["CityInChaosTRUE"] * 10)),
      sprintf("%+d", round(coefs["DownToEarthTRUE"] * 10)),
      sprintf("%+d", round(coefs["GoblinGearTRUE"] * 10)),
      sprintf("%+d", round(coefs["GuerrillaTacticsTRUE"] * 10)),
      sprintf("%+d", round(coefs["OsbornTechTRUE"] * 10)),
      sprintf("%+d", round(coefs["PersonalNightmareTRUE"] * 10)),
      sprintf("%+d", round(coefs["SinisterAssaultTRUE"] * 10)),
      sprintf("%+d", round(coefs["SymbioticStrengthTRUE"] * 10)),
      sprintf("%+d", round(coefs["WhispersOfParanoiaTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["ArmadilloTRUE"] * 10)),
      sprintf("%+d", round(coefs["ZzzaxTRUE"] * 10)),
      sprintf("%+d", round(coefs["InheritorsTRUE"] * 10)),
      sprintf("%+d", round(coefs["ISSinisterSixTRUE"] * 10)),
      sprintf("%+d", round(coefs["DeathstrikeTRUE"] * 10)),
      sprintf("%+d", round(coefs["ShadowKingTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["AcolytesTRUE"] * 10)),
      sprintf("%+d", round(coefs["BrotherhoodTRUE"] * 10)),
      sprintf("%+d", round(coefs["FuturePastTRUE"] * 10)),
      sprintf("%+d", round(coefs["MystiqueTRUE"] * 10)),
      sprintf("%+d", round(coefs["SentinelsTRUE"] * 10)),
      sprintf("%+d", round(coefs["ZeroToleranceTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["CrimeTRUE"] * 10)),
      sprintf("%+d", round(coefs["FantasyTRUE"] * 10)),
      sprintf("%+d", round(coefs["HorrorTRUE"] * 10)),
      sprintf("%+d", round(coefs["SciFiTRUE"] * 10)),
      sprintf("%+d", round(coefs["SitcomTRUE"] * 10)),
      sprintf("%+d", round(coefs["WesternTRUE"] * 10)),
      sprintf("%+d", round(coefs["LongshotTRUE"] * 10)),
      "",
      sprintf("%+d", round(coefs["DifficultyLevelExpert"] * 10)),
      sprintf("%+d", round(coefs["Heroic"] * 10)),
      sprintf("%+d", round(coefs["SkirmishLevel1"] * 10)),
      sprintf("%+d", round(coefs["SkirmishLevel2"] * 10)),
      sprintf("%+d", round(coefs["Standard2TRUE"] * 10)),
      sprintf("%+d", round(coefs["Expert2TRUE"] * 10))
    )
  ))
}