MarvelHeroes <- function(marvelGlm) {
  coefs <- coef(marvelGlm)
  ratings <- c(
       sprintf("%+d", round(coefs["AngelTRUE"] * 10)),
       sprintf("%+d", round(coefs["AdamWarlockTRUE"] * 10)),
       sprintf("%+d", round(coefs["AntManTRUE"] * 10)),
       sprintf("%+d", round(coefs["BishopTRUE"] * 10)),
       sprintf("%+d", round(coefs["BlackPantherTRUE"] * 10)),
       sprintf("%+d", round(coefs["BlackWidowTRUE"] * 10)),
       sprintf("%+d", round(coefs["CableTRUE"] * 10)),
       sprintf("%+d", round(coefs["CaptainAmericaTRUE"] * 10)),
       sprintf("%+d", round(coefs["CaptainMarvelTRUE"] * 10)),
       sprintf("%+d", round(coefs["ColossusTRUE"] * 10)),
       sprintf("%+d", round(coefs["CyclopsTRUE"] * 10)),
       sprintf("%+d", round(coefs["DeadpoolTRUE"] * 10)),
       sprintf("%+d", round(coefs["DoctorStrangeTRUE"] * 10)),
       sprintf("%+d", round(coefs["DominoTRUE"] * 10)),
       sprintf("%+d", round(coefs["DraxTRUE"] * 10)),
       sprintf("%+d", round(coefs["GambitTRUE"] * 10)),
       sprintf("%+d", round(coefs["GamoraTRUE"] * 10)),
       sprintf("%+d", round(coefs["GhostSpiderTRUE"] * 10)),
       sprintf("%+d", round(coefs["GrootTRUE"] * 10)),
       sprintf("%+d", round(coefs["HawkeyeTRUE"] * 10)),
       sprintf("%+d", round(coefs["HulkTRUE"] * 10)),
       sprintf("%+d", round(coefs["IronManTRUE"] * 10)),
       sprintf("%+d", round(coefs["IronheartTRUE"] * 10)),
       sprintf("%+d", round(coefs["MagikTRUE"] * 10)),
       sprintf("%+d", round(coefs["MsMarvelTRUE"] * 10)),
       sprintf("%+d", round(coefs["NebulaTRUE"] * 10)),
       sprintf("%+d", round(coefs["NovaTRUE"] * 10)),
       sprintf("%+d", round(coefs["PhoenixTRUE"] * 10)),
       sprintf("%+d", round(coefs["PsylockeTRUE"] * 10)),
       sprintf("%+d", round(coefs["RogueTRUE"] * 10)),
       sprintf("%+d", round(coefs["QuicksilverTRUE"] * 10)),
       sprintf("%+d", round(coefs["RocketRaccoonTRUE"] * 10)),
       sprintf("%+d", round(coefs["ScarletWitchTRUE"] * 10)),
       sprintf("%+d", round(coefs["ShadowcatTRUE"] * 10)),
       sprintf("%+d", round(coefs["SheHulkTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpdrTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpectrumTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpiderHamTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpiderManTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpiderManMilesMoralesTRUE"] * 10)),
       sprintf("%+d", round(coefs["SpiderWomanTRUE"] * 10)),
       sprintf("%+d", round(coefs["StarLordTRUE"] * 10)),
       sprintf("%+d", round(coefs["StormTRUE"] * 10)),
       sprintf("%+d", round(coefs["ThorTRUE"] * 10)),
       sprintf("%+d", round(coefs["ValkyrieTRUE"] * 10)),
       sprintf("%+d", round(coefs["VenomTRUE"] * 10)),
       sprintf("%+d", round(coefs["VisionTRUE"] * 10)),
       sprintf("%+d", round(coefs["WarMachineTRUE"] * 10)),
       sprintf("%+d", round(coefs["WaspTRUE"] * 10)),
       sprintf("%+d", round(coefs["WolverineTRUE"] * 10)),
       sprintf("%+d", round(coefs["X23TRUE"] * 10))
     )
  soloRatings = c(
      sprintf("%+d", round((coefs["AngelTRUE"] + coefs["AngelSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["AdamWarlockTRUE"] + coefs["AdamWarlockSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["AntManTRUE"] + coefs["AntManSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["BishopTRUE"] + coefs["BishopSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["BlackPantherTRUE"] + coefs["BlackPantherSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["BlackWidowTRUE"] + coefs["BlackWidowSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["CableTRUE"] + coefs["CableSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["CaptainAmericaTRUE"] + coefs["CaptainAmericaSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["CaptainMarvelTRUE"] + coefs["CaptainMarvelSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["ColossusTRUE"] + coefs["ColossusSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["CyclopsTRUE"] + coefs["CyclopsSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["DeadpoolTRUE"] + coefs["DeadpoolSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["DoctorStrangeTRUE"] + coefs["DoctorStrangeSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["DominoTRUE"] + coefs["DominoSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["DraxTRUE"] + coefs["DraxSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["GambitTRUE"] + coefs["GambitSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["GamoraTRUE"] + coefs["GamoraSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["GhostSpiderTRUE"] + coefs["GhostSpiderSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["GrootTRUE"] + coefs["GrootSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["HawkeyeTRUE"] + coefs["HawkeyeSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["HulkTRUE"] + coefs["HulkSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["IronManTRUE"] + coefs["IronManSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["IronheartTRUE"] + coefs["IronheartSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["MagikTRUE"] + coefs["MagikSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["MsMarvelTRUE"] + coefs["MsMarvelSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["NebulaTRUE"] + coefs["NebulaSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["NovaTRUE"] + coefs["NovaSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["PhoenixTRUE"] + coefs["PhoenixSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["PsylockeTRUE"] + coefs["PsylockeSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["RogueTRUE"] + coefs["RogueSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["QuicksilverTRUE"] + coefs["QuicksilverSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["RocketRaccoonTRUE"] + coefs["RocketRaccoonSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["ScarletWitchTRUE"] + coefs["ScarletWitchSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["ShadowcatTRUE"] + coefs["ShadowcatSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SheHulkTRUE"] + coefs["SheHulkSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpdrTRUE"] + coefs["SpdrSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpectrumTRUE"] + coefs["SpectrumSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpiderHamTRUE"] + coefs["SpiderHamSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpiderManTRUE"] + coefs["SpiderManSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpiderManMilesMoralesTRUE"] + coefs["SpiderManMilesMoralesSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["SpiderWomanTRUE"] + coefs["SpiderWomanSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["StarLordTRUE"] + coefs["StarLordSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["StormTRUE"] + coefs["StormSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["ThorTRUE"] + coefs["ThorSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["ValkyrieTRUE"] + coefs["ValkyrieSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["VenomTRUE"] + coefs["VenomSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["VisionTRUE"] + coefs["VisionSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["WarMachineTRUE"] + coefs["WarMachineSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["WaspTRUE"] + coefs["WaspSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["WolverineTRUE"] + coefs["WolverineSoloTRUE"]) * 10)),
      sprintf("%+d", round((coefs["X23TRUE"] + coefs["X23SoloTRUE"]) * 10))
    )
  return(data.frame(
    row.names = c(
      "Angel",
      "Adam Warlock",
      "Ant-Man",
      "Black Panther",
      "Black Widow",
      "Cable",
      "Captain America",
      "Captain Marvel",
      "Colossus",
      "Cyclops",
      "Deadpool",
      "Doctor Strange",
      "Domino",
      "Drax",
      "Gambit",
      "Gamora",
      "Ghost-Spider",
      "Groot",
      "Hawkeye",
      "Hulk",
      "Iron Man",
      "Ironheart",
      "Ms. Marvel",
      "Nebula",
      "Nova",
      "Phoenix",
      "Psylocke",
      "Rogue",
      "Quicksilver",
      "Rocket Raccoon",
      "Scarlet Witch",
      "Shadowcat",
      "She-Hulk",
      "SP//dr",
      "Spectrum",
      "Spider-Ham",
      "Spider-Man",
      "Spider-Man (Miles Morales)",
      "Spider-Woman",
      "Star-Lord",
      "Storm",
      "Thor",
      "Valkyrie",
      "Venom",
      "Vision",
      "War Machine",
      "Wasp",
      "Wolverine",
      "X-23"
    ),
    Ratings = ratings,
    Solo = soloRatings
  ))
}
